[package]
name = "t-rex-webserver"
version = "0.9.9"
description = "vector tile server"
repository = "https://github.com/t-rex-tileserver/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
build = "build.rs"
workspace = ".."

[lib]
doctest = false

[dependencies]
nickel = "0.10"
hyper = "~0.10" # same as nickel
serde_json = "1.0"
rustc-serialize = "0.3"
toml = "0.4"
clap = "2.31"
log = "0.4"
env_logger = "0.5"
open = "1.2"

[dependencies.t-rex-core]
path = "../t-rex-core"

[dependencies.t-rex-service]
path = "../t-rex-service"
