[package]
name = "t-rex-gdal"
version = "0.9.9"
description = "vector tile server"
repository = "https://github.com/t-rex-tileserver/t-rex"
readme = "../README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]
workspace = ".."

[lib]
doctest = false

[dependencies]
gdal = "0.4"
log = "0.4"

[dependencies.t-rex-core]
path = "../t-rex-core"
